security:
    always_authenticate_before_granting: true
    encoders:
        Podorozhny\Model\Backend\User:
            algorithm: sha512
            iterations: 500
            encode_as_base64: false
    providers:
        backend_user_provider:
            id: podorozhny.security.backend_user_provider
    firewalls:
        backend:
            host: %podorozhny.domain_main%
            pattern: ^/
            form_login:
                provider: backend_user_provider
                username_parameter: backend_login[email]
                password_parameter: backend_login[password]
                csrf_parameter: backend_login[csrf_token]
                csrf_provider: form.csrf_provider
                intention: backend_login
            logout:
                path: /logout
                target: /login
            anonymous: true
            remember_me:
                key: %secret%
                name: BACKEND_REMEMBER_ME
                lifetime: 31536000
                always_remember_me: true
        dev:
            pattern: ^/(_(profiler|wdt)|bundles|css|fonts|img|js)/
            security: false
    access_control:
        - { host: %podorozhny.domain_main%, path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { host: %podorozhny.domain_main%, path: ^/user, roles: ROLE_PERSONNEL }
        - { host: %podorozhny.domain_main%, path: ^/finance, roles: ROLE_FINANCE }
        - { host: %podorozhny.domain_main%, path: ^/warehouse, roles: ROLE_WAREHOUSE }
        - { host: %podorozhny.domain_main%, path: ^/clients, roles: ROLE_CLIENTS }
        - { host: %podorozhny.domain_main%, path: ^/, roles: [ROLE_PERSONNEL, ROLE_FINANCE, ROLE_WAREHOUSE, ROLE_CLIENTS] }