Podorozhny\Model\Backend\User:
    properties:
        name:
            - NotBlank:
                message: validation.not_blank
            - Length:
                min: 2
                max: 100
                minMessage: validation.length.min
                maxMessage: validation.length.max
        email:
            - NotBlank:
                message: validation.not_blank
            - Length:
                max: 255
                maxMessage: validation.length.max
            - Email:
                message: validation.email
        plainPassword:
            - NotBlank:
                message: validation.not_blank
            - Length:
                min: 8
                max: 4096
                minMessage: validation.length.min
                maxMessage: validation.length.max