services:
    podorozhny.controller.backend_security:
        class: Podorozhny\CoreBundle\Controller\Backend\SecurityController
        parent: podorozhny.controller.abstract
        arguments:
            - @podorozhny.manager.backend_user

    podorozhny.controller.backend_page:
        class: Podorozhny\CoreBundle\Controller\Backend\PageController
        parent: podorozhny.controller.abstract