Podorozhny\Model\Backend\UserGroup:
    type: entity
    table: backend_user_groups
    repositoryClass: Podorozhny\Doctrine\Repository\Backend\UserGroupRepository
    oneToMany:
        users:
            targetEntity: Podorozhny\Model\Backend\User
            mappedBy: group
            orderBy:
                createdAt: ASC
    manyToMany:
        roles:
            targetEntity: Podorozhny\Model\Backend\Role
            inversedBy: groups
            joinTable:
                name: backend_usergroup_role_relations
                joinColumns:
                    group_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    role_id:
                        referencedColumnName: id
            orderBy:
                name: ASC
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            options:
                unsigned: true
    fields:
        createdAt:
            column: created_at
            type: datetime
        name:
            type: string
            length: 255
            unique: true