Podorozhny\Model\Backend\User:
    type: entity
    table: backend_users
    repositoryClass: Podorozhny\Doctrine\Repository\Backend\UserRepository
    manyToMany:
        groups:
            targetEntity: Podorozhny\Model\Backend\UserGroup
            inversedBy: users
            joinTable:
                name: backend_user_usergroup_relations
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id
            orderBy:
                name: ASC
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            options:
                unsigned: true
    fields:
        createdAt:
            column: created_at
            type: datetime
        email:
            type: string
            length: 255
        emailCanonical:
            column: email_canonical
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: 128
        salt:
            type: string
            length: 32
        firstname:
            type: string
            length: 100
        lastname:
            type: string
            length: 100