services:
    podorozhny.controller.finance_transaction:
        class: Podorozhny\CoreBundle\Controller\Finance\TransactionController
        parent: podorozhny.controller.abstract
        arguments:
            - @podorozhny.entity_manager
            - @knp_paginator
            - @podorozhny.manager.finance_transaction