Podorozhny\Model\Warehouse\Good:
    type: entity
    table: warehouse_goods
    repositoryClass: Podorozhny\Doctrine\Repository\Warehouse\GoodRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            options:
                unsigned: true
    fields:
        createdAt:
            column: created_at
            type: datetime
        name:
            type: string
            length: 100
        description:
            type: string
            length: 5000
            nullable: true
        count:
            type: integer
            options:
                unsigned: true
        width:
            type: integer
            options:
                unsigned: true
        height:
            type: integer
            options:
                unsigned: true
        depth:
            type: integer
            options:
                unsigned: true
        weight:
            type: integer
            options:
                unsigned: true